#!/bin/sh

#SBATCH -A DBS21007
#SBATCH --job-name=ds000117-fmriprep
#SBATCH --mail-type=END
#SBATCH --mail-user=jbwexler@tutanota.com
#SBATCH --output=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000117-fmriprep/.reproman/jobs/local/20220208-161600-21f2/stdout
#SBATCH --error=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000117-fmriprep/.reproman/jobs/local/20220208-161600-21f2/stderr

#SBATCH --nodes=5
#SBATCH --ntasks=17
#SBATCH --time=48:00:00
#SBATCH --partition=normal

metadir=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000117-fmriprep/.reproman/jobs/local/20220208-161600-21f2

module load launcher
module load remora
export LAUNCHER_JOB_FILE="$metadir/launcher"

for task_id in $(seq 0 16); do
    printf "$metadir/runscript %d >$metadir/stdout.%d 2>$metadir/stderr.%d\n" \
      "$task_id" "$task_id" "$task_id" >>"$LAUNCHER_JOB_FILE"
done

remora "$LAUNCHER_DIR"/paramrun